weather:
  # In which worlds weather control is allowed?
  # If a world doesn't exist nothing will happen
  worlds:
  - world
  - second_world
  - third_world
  # "point" for a static location
  # "player" for using the player's location
  source: point
  point:
    latitude: 41.84201
    longitude: -89.485937
  player:
    geolite2_accountId: 710438
    geolite2_apiKey: 'qLeseHp4QNQcqRGn'

provider:
  # Your provider choice
  # Case insensitive
  choice: openweathermap
  # Provider settings here
  # Unlike the previous option, these are case sensitive
  openweathermap:
    apiKey: 'd3d37fd3511ef1d4b44c7d574e9b56b8'
  # More providers soon!

settings:
  # Delay between rechecking weather
  # 20 is one second
  # Shouldn't affect performance
  timeBetweenRecheck: 600
  # Whether to broadcast messages about weather updates
  broadcast: false

  # Advanced options
  timeBeforeInitialRun: 0
  debug: false
  debugAllowDox: false