weather:
  # In which worlds weather control is allowed?
  # If a world doesn't exist nothing will happen
  worlds:
  - world
  - second_world
  - third_world
  # Point for a static location
  # Weather by player's real location soon
  source: point
  point:
    latitude: 41.84201
    longitude: -89.485937

provider:
  # Your provider choice
  # Case insensitive
  choice: openweathermap
  # Provider settings here
  # Unlike the previous option, these are case sensitive
  openweathermap:
    apiKey: ''
  # More providers soon!

settings:
  # Delay between rechecking weather
  # 20 is one second
  # Shouldn't affect performance
  timeBetweenRecheck: 600

  # Advanced options
  timeBeforeInitialRun: 0
  debug: true