weather:
  enabled: true

  worlds:
  - world
  - second_world
  - third_world

  provider:
    # Weather provider
    choice: openweathermap
    # Configure it here
    openweathermap:
      apiKey: 'd3d37fd3511ef1d4b44c7d574e9b56b8' # PLEASE get your own @ https://home.openweathermap.org/users/sign_up
    # More providers soon!

map:
  # "point" - static location
  # "player" - player's IP location (fake weather)
  # "globe" - world resembles a real-world globe
  type: point

  point:
    latitude: 41.84201
    longitude: -89.485937

  player:
    empty: for now

  globe:
    # Valid latitude range: -90 to 90
    # Valid longitude range: -180 to 180
    # 1 degree of latitude and longitude is about 111 km
    # The defaults here assume 1 block = ~1 km
    # 1 block = <scale> degrees
    scale_latitude: 0.009
    scale_longitude: 0.009

    # What to do if player exceeds the range specified above
    # false - do nothing (clamp to nearest allowed value)
    # true - wrap the number
    # for example; if a player's position on map converts to 94 degrees (out of bounds), it becomes -86 degrees
    wrap: true

time:
  # warning: this removes sleep
  enabled: false

  worlds:
  - world

  # "auto" to use server's timezone
  # Alternatively choose one of these: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
  # WARNING: it is purely cosmetical 
  timezone: 'auto'

  # x day cycles / 24 hrs
  # basically how many Minecraft days during a real day
  scale: 1.0

  # time based on... time?
  # each player has time offset like timezones
  # uses timezone as base, unless auto
  # uses settings from map
  per_player: false