name: RealWeather
version: ${project.version}
api-version: 1.16
author: Minecon724
main: pl.minecon724.realweather.RW
libraries:
  - org.json:json:20220320
  - com.maxmind.geoip2:geoip2:4.1.0
commands:
  realweather:
    alias: rw
    description: RealWeather main command