name: RealWeather
version: ${project.version}
api-version: 1.16
load: STARTUP
author: Minecon724
main: pl.minecon724.realweather.RW
libraries:
  - org.json:json:20231013
  - com.maxmind.geoip2:geoip2:4.2.0